# -*- eval: (ansible 1) -*-
- name: Freya setup
  hosts: freya
  become: true
  tasks:
    - name: Hostname is set correctly
      hostname:
        name: freya.home.mpardalos.com

    - name: Packages
      dnf:
        name:
          - nfs-utils
          - podman
          - podman-plugins
        state: present

    - name: container user and group exists
      user:
        name: container
        uid: 5000

    - name: /data directory exists
      file:
        path: /data
        state: directory

    - name: Data directory is mounted
      mount:
        src: freyr.home.mpardalos.com:/data
        path: /data
        state: mounted
        fstype: nfs

    - tags: olivetin
      block:
        - name: OliveTin package
          dnf:
            name: https://github.com/OliveTin/OliveTin/releases/download/2024.03.24/OliveTin_linux_amd64.rpm
            disable_gpg_check: true
            state: present

        - name: OliveTin config is present
          copy:
            src: files/olivetin-config.yaml
            dest: /etc/OliveTin/config.yaml
          register: olivetin_config

        - name: OliveTin service is enabled
          systemd:
            name: OliveTin.service
            state: started
            enabled: true
          register: olivetin_service

        - name: OliveTin config reload
          systemd:
            name: OliveTin.service
            state: restarted
          when: olivetin_config.changed and not olivetin_service.changed

    - name: Firewall config
      firewalld:
        service: "{{ item }}"
        state: enabled
        immediate: true
        permanent: true
      with_items:
        - http
        - https

    - name: Scripts
      copy:
        src: files/scripts/qb-rst
        dest: /usr/local/bin/
        owner: root
        group: root
        mode: u=rwx,g=rwx,o=rx

- name: Containers
  import_playbook: containers.yaml
