# -*- eval: (ansible 1) -*-
- name: Freyr setup
  hosts: freyr
  become: true
  tasks:
    - name: Hostname is set correctly
      hostname:
        name: freyr.home.mpardalos.com

    - name: Packages
      dnf:
        name:
          - samba
          - qemu-guest-agent

    - name: Disk mount
      mount:
        src: UUID=f2e7e959-0e92-46a0-b53f-9a4f3609d9fa
        path: /data
        state: mounted
        fstype: btrfs

    - name: Samba config
      copy:
        src: freyr_smb.conf
        dest: /etc/samba/smb.conf
      register: smb_config

    - name: Samba service
      systemd:
        name: smb
        enabled: true
        state: started

    - name: Reload samba service
      systemd:
        name: smb
        state: reloaded
      when: smb_config.changed

    - name: NFS exports
      copy:
        src: freyr_exports
        dest: /etc/exports
      register: nfs_config

    - name: Samba service
      systemd:
        name: nfs-server
        enabled: true
        state: started

    - name: Reload nfs service
      systemd:
        name: nfs-server
        state: reloaded
      when: nfs_config.changed

    - name: Firewall services
      firewalld:
        service: "{{ item }}"
        permanent: true
        immediate: true
        state: enabled
      with_items:
        - cockpit
        - dhcpv6-client
        - mdns
        - mountd
        - nfs
        - rpc-bind
        - samba
        - ssh
        - zabbix-agent

    - name: Firewall ports
      firewalld:
        port: 111/tcp
        permanent: true
        immediate: true
        state: enabled
